version: '3.7'

services:
  ssh:
    build:
      context: ssh
      target: development
    volumes:
      - ./ssh:/go/src/github.com/shellhub-io/shellhub/ssh
  api:
    build:
      context: api
      target: development
    volumes:
      - ./api:/go/src/github.com/shellhub-io/shellhub/api
  ws:
    build:
      context: ws
      target: development
    volumes:
      - ./ws:/go/src/github.com/shellhub-io/shellhub/ws
  ui:
    build:
      context: ui
      target: development
    volumes:
      - ./ui:/src
  gateway:
    build:
      context: gateway
  agent:
    build:
      context: agent
      target: development
    environment:
      - SERVER_ADDRESS=http://172.17.0.1:80
      - PRIVATE_KEY=/var/run/secrets/shellhub.key
    volumes:
      - ./agent:/go/src/github.com/shellhub-io/shellhub/agent
    depends_on:
      - emq
      - api
      - ssh
      - gateway
