version: '3.7'

services:
  ssh:
    build: ssh
    environment:
      - PRIVATE_KEY=/var/run/secrets/ssh_private_key
    depends_on:
      - emq
    links:
      - emq
    ports:
      - "2222:2222"
    secrets:
      - ssh_private_key
  emq:
    image: emqx/emqx:v3.1.1
    environment:
     - EMQ_NAME=emq
     - EMQ_HOST=127.0.0.1
     - EMQ_LOG__CONSOLE__LEVEL=debug
    ports:
    - target: 1883
      published: 1883
      protocol: tcp
      mode: host
    - target: 18083
      published: 18083
      protocol: tcp
      mode: host
  api:
    environment:
      - PRIVATE_KEY=/var/run/secrets/api_private_key
      - PUBLIC_KEY=/var/run/secrets/api_public_key
    depends_on:
      - mongo
    links:
      - mongo
    secrets:
      - api_private_key
      - api_public_key
  gateway:
    build: gateway
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - api
    ports:
      - '80:80'
  mongo:
    image: mongo:3.4.19

secrets:
  ssh_private_key:
    external: true
  api_private_key:
    external: true
  api_public_key:
    external: true
