version: '3.7'

services:
  ssh:
    build:
      context: ssh
      target: development
    volumes:
      - ./ssh:/go/src/github.com/gustavosbarreto/devicehub/ssh
      - secrets:/var/run/secrets
  api:
    build:
      context: api
      target: development
    volumes:
      - ./api:/go/src/github.com/gustavosbarreto/devicehub/api
      - secrets:/var/run/secrets
  agent:
    build:
      context: agent
      target: development
    environment:
      - SERVER_ADDRESS=http://172.17.0.1:80
      - PRIVATE_KEY=/root/devicehub.key
    volumes:
      - ./agent:/go/src/github.com/gustavosbarreto/devicehub/agent
      - secrets:/var/run/secrets

volumes:
  secrets:
