version: 2.1

executors:
  docker:
    environment:
      API_IMAGE_NAME: gustavosbarreto/devicehub-api
      SSH_IMAGE_NAME: gustavosbarreto/devicehub-ssh
      WS_IMAGE_NAME: gustavosbarreto/devicehub-ws
      UI_IMAGE_NAME: gustavosbarreto/devicehub-ui
      GATEWAY_IMAGE_NAME: gustavosbarreto/devicehub-gateway
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API microservice
          working_directory: api
          command: docker build -t $API_IMAGE_NAME:latest .
      - run:
          name: Build SSH microservice
          working_directory: ssh
          command: docker build -t $SSH_IMAGE_NAME:latest .
      - run:
          name: Build WS microservice
          working_directory: ws
          command: docker build -t $WS_IMAGE_NAME:latest .
      - run:
          name: Build UI microservice
          working_directory: ui
          command: docker build -t $UI_IMAGE_NAME:latest .
      - run:
          name: Build API Gateway microservice
          working_directory: ui
          command: docker build -t $GATEWAY_IMAGE_NAME:latest .
      - run:
          name: Archive Docker images
          command: |
            docker save $(docker images | awk '{if ($1 ~ /\/devicehub-/) print $3}') -o images.tar
            docker images | awk '{if ($1 ~ /\/devicehub-/) print $1 " " $3}' > tags.txt
      - persist_to_workspace:
          root: .
          paths:
            - ./images.tar
            - ./tags.txt
  push:
    executor: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Setup DockerHub credentials
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Load archived Docker images
          command: |
            docker load -i /tmp/workspace/images.tar
            awk '{ print "docker tag "$2" "$1"" | "/bin/sh"}' /tmp/workspace/tags.txt
      - run:
          name: Publish API microservice image
          command: docker push $API_IMAGE_NAME:latest
      - run:
          name: Publish SSH microservice image
          command: docker push $SSH_IMAGE_NAME:latest
      - run:
          name: Publish WS microservice image
          command: docker push $WS_IMAGE_NAME:latest
      - run:
          name: Publish UI microservice image
          command: docker push $UI_IMAGE_NAME:latest
      - run:
          name: Publish API Gateway microservice image
          command: docker push $GATEWAY_IMAGE_NAME:latest
workflows:
  version: 2
  master:
    jobs:
      - build:
          filters:
            branches:
              only: master    
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
