version: 2

jobs:
  build:
    environment:
      API_IMAGE_NAME: gustavosbarreto/devicehub-api
      SSH_IMAGE_NAME: gustavosbarreto/devicehub-ssh
      WS_IMAGE_NAME: gustavosbarreto/devicehub-ws
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API microservice
          working_directory: api
          command: docker build -t $API_IMAGE_NAME:latest .
      - run:
          name: Build SSH microservice
          working_directory: ssh
          command: docker build -t $SSH_IMAGE_NAME:latest .
      - run:
          name: Build WS microservice
          working_directory: ws
          command: docker build -t $WS_IMAGE_NAME:latest .

workflows:
  version: 2
  master:
    jobs:
      - build:
          filters:
            branches:
              only: master    
